# Generated by Django 4.1.7 on 2023-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correos_enviados',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=15, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
