# Generated by Django 4.1.7 on 2023-04-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correos_enviados',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
